name: Generator Keystore (Sekali Pakai)

on:
  workflow_dispatch: # Supaya bisa di-klik manual tombol "Run"

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
    - name: 🔑 Generate Keystore
      run: |
        # Membuat kunci permanen otomatis
        keytool -genkey -noprompt \
        -v -keystore my_release.keystore \
        -alias mykey \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass 123456 \
        -keypass 123456 \
        -dname "CN=Gl4es User, OU=Android, O=Github, L=Indo, S=ID, C=ID"
        
    - name: 📤 Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: FILE_KUNCI_RAHASIA
        path: my_release.keystore